load("@build_bazel_rules_apple//apple:macos.bzl", "macos_dylib")
load("//build_tools/bazel:build_defs.oss.bzl", "iree_runtime_cc_library")

iree_runtime_cc_library(
    name = "client",
    srcs = ["client.cc"],
    hdrs = ["client.h"],
    copts = ["-Wno-unused-variable"],
    includes = ["../.."],
    deps = [
        "//integrations/pjrt/src/iree_pjrt/common",
        "//runtime/src/iree/hal/drivers/metal",
        "//runtime/src/iree/hal/drivers/metal/registration",
    ],
)

iree_runtime_cc_library(
    name = "dylib",
    srcs = [
        "dylib_entry_point.cc",
    ],
    defines = ["PJRT_PLUGIN_BUILDING_LIBRARY"],
    linkopts = ["-Wl,-exported_symbol,_GetPjrtApi"],
    deps = [
        ":client",
        "//integrations/pjrt/src/iree_pjrt/common",
        "//integrations/pjrt/src/iree_pjrt/common:dylib_platform",
    ],
    alwayslink = True,
)

macos_dylib(
    name = "pjrt_plugin_iree_metal",
    minimum_os_version = "15.0",
    deps = [":dylib"],
)
